### ISSUE TITLE
Incorrect coercion to unsigned 32-bit integers?

### ISSUE THREAD

**Issue by shelby3** [dchest/tweetnacl-js#104]
I noticed [the code](https://github.com/dchest/tweetnacl-js/blob/master/nacl.js#L104) is employing a _signed_ 32-bit integer coercion, where it appears an _unsigned_ coercion is intended.

The [unsigned coercion in JavaScript](http://speakingjs.com/es5/ch11.html#_shift_operators) is `x >>> 0` not `x | 0`.

It doesn't appear to me that the specific usage would cause any change in binary result, but it begs for bug if ever combined with arithmetic, does impact code readability (intent), and perhaps impacts performance since the coerced signed value is I presume coerced again to an unsigned value when it is assigned to an element of the `Uint32Array`.

Additionally, there are [other instances](https://github.com/dchest/tweetnacl-js/blob/master/nacl.js#L94) in the code, where the coercion appears to be unnecessary because the usage (in the invoked function) is exclusively binary operators which perform the same coercion to 32-bits. Wouldn't it better for the functions enforce their input data types, which they already do without the apparently unnecessary coercion performed by the caller, rather than have the caller remember to enforce it every time. In other words, it seems to violate the software engineering principles of favoring a Single-Point-Of-Truth (SPOT) and DNRY.

**Comment by dchest** [comment]
It turns out in many cases doing `>>> 0` is slower than `| 0`. Signed coercion or unsigned coertion doesn't matter in most cases for the arithmetic we use: for Salsa20/8 in [scrypt-async-js](https://github.com/dchest/scrypt-async-js) I even use `Int32Array` instead of `Uint32Array`, because it turned out they work faster (up to 2x in some versions of Safari), and only at the end convert result to unsigned. I also thought that keeping numbers unsigned when doing arithmetics and then putting them `Uint32Array` will be faster, but it turned out to be false for the cases I measured.

I should note that there are a lot of tests in TweetNaCl-js, which even discovered coercion bug in old Safari versions — see https://github.com/dchest/tweetnacl-js/commit/e13ba848208ab5fd9717f87dbb4e45294269662b — so that additional unnecessary `| 0` is there for a reason.

If you find cases where we can use `>>> 0` instead of `| 0` and it doesn't impact performance or correctness (run tests and benchmarks to verify), please feel free to send pull requests — I'd be happy to accept them.

**Comment by shelby3** [comment]
Thanks for explaining your experience. I am delighted I am now aware of those caveats.

However, regarding the last paragraph of my OP, wouldn't it be better to put the `|0` in the functions instead of the caller needing to remember to add them. It would also I think be more clear then that it is some strange bug workaround, as is the case with the `[e13ba84](https://github.com/dchest/tweetnacl-js/commit/e13ba848208ab5fd9717f87dbb4e45294269662b)` you cited for me.

And since this is the reference version of the code and not the fast version, I think I would have preferred `|0 >>> 0` for clarity of intent instead of just `|0 >>> 0`. Seeing that consistently every where I think would make it less confusing for those who don't know already these caveats.

Any way, I am nitpicking. No changes really needed.

**Comment by dchest** [comment]
I think `u64` is already called with only 32-bit integers (results of bitwise operations) everywhere, so `| 0` would be unnecessary. For example,

`new u64((b / 0x20000000) | 0, b << 3))`

why do `b << 3 | 0` if it's already clear that it's a bitwise operation?

**Comment by shelby3** [comment]
Unless I am misunderstanding you, I believe I was suggesting the antithesis, which is don't expect the caller to enforce the coercions and instead put them in the functions that depend on the coercions. I was specifically thinking of the case I linked to:

> Additionally, there are [other instances](https://github.com/dchest/tweetnacl-js/blob/master/nacl.js#L94) in the code

I am thinking the `|0` would ideally be moved into the `L32()` and [`st32()`](https://github.com/dchest/tweetnacl-js/blob/master/nacl.js#L114) functions.

The [`u64()` constructor](https://github.com/dchest/tweetnacl-js/blob/master/nacl.js#L10) is already enforcing `|0`.

**Comment by dchest** [comment]
Oh, I see what you mean.
