### ISSUE TITLE
Feature request - Argon2

### ISSUE THREAD

**Issue by paulg446** [dchest/tweetnacl-js#121]
Any chance of implementing Argon2 as a replacement for Scrypt? https://download.libsodium.org/libsodium/content/password_hashing/

**Comment by dchest** [comment]
No, TweetNaCl.js is intended to be a pure port of TweetNaCl, not libsodium-like library, there will be no other crypto primitives in it. See also #102.

In addition to that, I wouldn't suggest using a JavaScript implementation of Argon2, since it requires 64-bit integers for good performance, which JavaScript doesn't have. Argon2 in JavaScript will be too slow compared to attacker's implementation, and thus provide more advantage to attackers. I suggest using scrypt instead (I have a fast implementation here: [scrypt-async-js](https://github.com/dchest/scrypt-async-js), which is only ~1.5-2x slower than the native one.)

**Comment by paulg446** [comment]
I see. Thanks anyway for the insight regarding Argon2 - I'll stick with Scrypt (I'm already using your fantastic async implementation).
