### ISSUE TITLE
Issue with Unlicense - fallback?

### ISSUE THREAD

**Issue by narcoticfresh** [dchest/tweetnacl-js#125]
Hey guys..

We use this project in some of our products (it gets pulled in by npm magic)..

Now, we have a small issue in that the "Unlicense" (which this project uses) is not really compatible to local laws here in Switzerland. Specifically, it's not "legal" to give copyright away - if you do something, you are still the author and still hold copyright - the public domain cannot hold a copyright.

This could easily be solved by stating something like this in the `LICENSE` file:

> In jurisdictions that don't recognize the public domain as a copyright holder, the MIT license serves as a fallback license.

Well, I'm not a lawyer or anything ;-) But I guess that is sufficient..

Could you maybe add something like that?

Thanks so much

**Comment by dchest** [comment]
Please search this issue tracker for "license".

**Comment by narcoticfresh** [comment]
@dchest 
Ah, I see it went from non-SPDX to CC0-1.0 and then to Unlicense.. Hmm..

> also, did you read the terms of Unlicense?

Yes, i think i did.. Are you hinting at something that I may be missing? 

I didn't see a clause or anything in the Unlicense for places that don't allow giving away copyright completely (which yes, is _really_ stupid indeed)

Any input is greatly appreciated ;-)

**Comment by dchest** [comment]
It has a clause similar to MIT:

>  Anyone is free to copy, modify, publish, use, compile, sell, or
distribute this software, either in source code form or as a compiled
binary, for any purpose, commercial or non-commercial, and by any
means.

**Comment by dchest** [comment]
Hello, Brian. My relicensing would be pointless, as explained in numerous previous discussions in this issue tracker: I only [ported code, which is in public domain](https://github.com/dchest/tweetnacl-js/blob/master/AUTHORS.md#list-of-authors-of-third-party-public-domain-code-from-which-tweetnacljs-code-was-derived). If you can't use code that is in public domain, you can't use this code, because it's derived from public domain code.

**Comment by ilatypov** [comment]
The no-warranty clause of Unlicense contradicts the no-ownership clause, according to Rick Moen.  

https://lists.opensource.org/pipermail/license-review/2012-January/001386.html

"Public domain" means "no copyright" means "no license", according to OSI, https://opensource.org/faq#public-domain  This, I think, may prevent adoption of the npm module by enterprises because the license does not explicitly relieve recipients from patent infringement or from having to explore their warranty.  Sorry I am not a law specialist but I understood OSI's FAQ this way.

**Comment by dchest** [comment]
I soooooo sad that enterprises can't adopt this module. 🎻

**Comment by ilatypov** [comment]
Obviously, there may be companies not worrying enough about their open source usage.  There are tools available to track diverging licenses in the NodeJS or UI application, and a big company I know seems to be diligent enough to pay attention to proper usage rights.

OSI recommends some of the more conventional licenses such as MIT that seem to relieve recipients from worries (according to OSI's point of view).

**Comment by dchest** [comment]
@ilatypov please search this issue tracker for my numerous replies on why this particular public domain dedication is used, and why it would be pointless for me to use MIT for this project (it's also in my reply to Brian above).
