### ISSUE TITLE
Short Question Regarding Asymmetric and Symmetric Encryption

### ISSUE THREAD

**Issue by MoePad** [dchest/tweetnacl-js#130]
Hi,

thanks for porting NaCl to JavaScript!

I'm completly new to the topic of encryption and the NaCl library itself.

So I have a short question regarding asymmetric and symmetric encryption:

If I do this:

 `nacl.box(utf8message, utf8nonce, keyPair1.publicKey, keyPair2.secretKey)`

my expectation is that only the receiver (i.e. the guy with keyPair.privateKey) can encrypt the message. 

But if I do this:

`nacl.box.open(encryptedMessage, utf8nonce, keyPair1.publicKey, keyPair2.secretKey)`

I can decrypt the message.

Therefore, I assume that it is not really asymmetrical encrypted but only asymmetrical authenticated? Is this a right assumption?

Any clarification regarding nacl.box / nacl.secretbox and (a)symmetric encryption is highly appreciated. Thanks in advance!

**Comment by dchest** [comment]
Unlike in RSA, where you "asymetrically" encrypt things for the received that you cannot decrypt, here (in Diffie-Hellman [DH]) by combining receiver's public key with your secret key, you derive a common symmetrical key (which both you and the receiver knows, but nobody else), and then symmetrically encrypt (and authenticate!) plaintext with it. This means that both you and receiver can produce encrypted and authenticated boxes, and unless you keep track of it, you can't tell who encrypted and authenticated it. If you need to make sure authenticate the *origin* of encryption, you can, for example, sign it.

There's also a construction (not in TweetNaCl, but you can built it yourself) that allows you to make sure you (behaved according to protocol) can't decrypt the ciphertext in the future by using an ephemeral secret key instead of your own -- see https://download.libsodium.org/doc/public-key_cryptography/sealed_boxes.html

For DH, see https://en.wikipedia.org/wiki/Diffie%E2%80%93Hellman_key_exchange for more details.

**Comment by MoePad** [comment]
Thanks for the fast answer and clearification!
