### ISSUE TITLE
Generating keypair leaks memory

### ISSUE THREAD

**Issue by varjolintu** [dchest/tweetnacl-js#222]
It's possible that `nacl.box.keyPair()` leaks memory every time it's called. In KeePassXC-Browser that functions is called repeatedly in a reconnect situation.

Details in the related issue: https://github.com/keepassxreboot/keepassxc-browser/issues/1113

**Comment by CMEONE** [comment]
Hello @varjolintu I'll look into this issue, but do you have any more details such as what specific circumstances cause this leak (like how many times are you generating keys, in what time period, etc.)?

Also, are you using the latest version of TweetNaCl.js? If not, try updating to the latest version and see if that resolves the issue.

**Comment by varjolintu** [comment]
@CMEONE For now KeePassXC-Browser with Auto-Reconnect enabled generates a new keypair in one second intervals. Latest version didn't solve the problem. If testing this with KeePassXC-Browser is too much to handle, I can also make a simple browser extension where this bug can be easily reproduced.

**Comment by CMEONE** [comment]
@varjolintu So, I've run some tests and haven't found any significant increases in memory usage as shown by the constantly updating memory tab in devtools. The memory usage seems to just go up 1MB and then back down 1MB, oscillating between those two values with no real signs of leaks. I am running the key generation 10 times a second instead of once per second to try to make any results of the tests more noticeable. 
```javascript
setInterval(() => {
    let keypair = nacl.box.keyPair();
}, 100);
```
This is the code that I am using to test. As you can see, I keep the keypair scoped within the function call in the interval so that it becomes garbage collected eventually (the reason for the oscillation in memory usage) and doesn't consume a significant amount of memory, this way we can isolate any memory issues specifically to `nacl.box.keyPair()` (there doesn't seem to be any issue that I can see currently).

Could you please show a small sample of code that reproduces your issue so that we can further investigate?

**Comment by varjolintu** [comment]
@CMEONE You're correct. I made an example extension and it doesn't have the memory leak. So this is definitely a KeePassXC-Browser issue. Something is done in a way that the GC doesn't trigger. Sorry for the inconvenience. Closing the issue.

**Comment by CMEONE** [comment]
No problem, glad I was able to help isolate this issue to KeePassXC-Browser.

**Comment by dchest** [comment]
@CMEONE thank you for helping with this!

@varjolintu I noticed keys are stored in a "global" (namespaced) variable in KeePassXC-Browser extension, maybe this has something to do with the leak.

**Comment by CMEONE** [comment]
@dchest No problem! I did indeed see this global variable in KeePassXC-Browser and thought it was being overwritten with the new keys, but this could potentially be part of the issue.

**Comment by CMEONE** [comment]
@varjolintu Try using the memory tab in devtools to see what isn't being garbage collected.

**Comment by varjolintu** [comment]
I tried my example with a "global" variable, but that didn't reproduce the issue. Thanks for the tips.
