### ISSUE TITLE
Licensing library under MIT

### ISSUE THREAD

**Issue by gianpo86** [dchest/tweetnacl-js#260]
Hey there... thanks a lot for the great job so far!
Is there any plan to put any license information for the repository? Like MIT or so?

I have some projects with interdependencies from this great one and I was looking for solving some Licensing issues that I am facing in my company :)

Thanks!

**Comment by dchest** [comment]
https://github.com/dchest/tweetnacl-js/blob/master/LICENSE

**Comment by khlylkhatwnltfy** [comment]
kHello, I don't remember the last login at all and I haven't done any
operation myself. I returned the email with difficulty in a series of
programs over the course of a year and I was able to recover it with
difficulty. commercial and through Bluetooth and Wi-Fi, such as online
cards and coins, my personal Wi-Fi and wallets, stocks, currencies,
exchanges, tokens and calendars and all contacts and e-mails and
information inside it and work sites and cloud spaces and... They have
deleted all the information on my phone, laptop and flash drive. The
identification cards related to my social, economic, political affairs and
the police force are also available. There are many mi accounts created
with my information that I do not have access to.and business tools through
Bluetooth and Wi-Fi, such as online cards, coins, my personal Wi-Fi, and
wallets, stocks, currencies, exchanges, tokens, and calendars, and all
contacts, e-mails, and information inside it, and business sites and
spaces. They deleted the cloud and... and took all the information on the
phone, laptop and flash drive Identification cards related to my social,
economic, political affairs and the police force are also available. There
are many mi accounts created with my details that I do not have access to.
Safura Rezaei's email with the numbers 09369174690 and 09139284159 and
Yusuf Rezaei's email with the phone numbers 09135693241 and 091333312805
09393359338 and 09933386516 and
09939322100 and Yusuf Rezaei's national code is 1080118799, I have this
information from them

And the important point is that Safura Rezaei and Yusuf Rezaei baited their
sister Samane Rezaei and used Samane Rezaei's phone, emails and numbers and
did all these actions. He did not have them and he also did not have access
to his emails and was completely unaware. The number of people involved is
not completely clear because all the contacts and personal and business
information are available on my phone and website and it is not clear how
many people are involved. Please check and take action immediately and
inform me. My emails are not secure. They have all my personal information
such as national code and number and.. all my details and my government
information. The amount is 146 million dollars, 33.5 million dollars and
312 million dollars in the email khlylkhatwnltfy@ gmail.com is available as
blockchain. The emails of Khatoon 786898, Majid Lotfi Jalalabadi and Khalil
Khatoon Lotfi are my emails and they have also created a fake website with
my emails and details.call09923550876 to inform.


در تاریخ دوشنبه ۱۲ فوریه ۲۰۲۴،‏ ۱۳:۳۸ Dmitry Chestnykh <
***@***.***> نوشت:
