### ISSUE TITLE
2.0 or something revamped?

### ISSUE THREAD

**Issue by jamilservicos** [dchest/tweetnacl-js#263]
@dchest We are in a different time, computers are not what they used to be...
I suggest creating something in a language that supports wasm and napi, and porting it to the browser and nodejs via wasm and napi.
you will have less worry than something directly in javascript, since there are many "news" in javascript, constantly.
I don't know if it helps give you any ideas... but look at this suite I'm making in rust: https://github.com/SimplyBuilder/sb-module-crypto/

Maybe it will turn on some light for your "2.0".

you no longer need to struggle to write compact code, because in the end everyone is using heavy frameworks without caring about it.

**Comment by dchest** [comment]
There's no need for WASM/etc tweetnacl-js in the future: everything is moving towards supporting X25519 and Ed25519 natively via Web Cryptography API, which is great. There is a place for a tweetnacl-js-style wrapper (but async) for ease of use, but the cryptography code will be up to the browser/Node/Bun/etc runtime. Hashing hash been there already for a long time. Base64 encoding is coming to ArrayBuffer. UUID, if you need it, is crypto.randomUUID. Node implemented crypto.getRandomValues. Lovely progress!

**Comment by khlylkhatwnltfy** [comment]
kHello, I don't remember the last login at all and I haven't done any
operation myself. I returned the email with difficulty in a series of
programs over the course of a year and I was able to recover it with
difficulty. commercial and through Bluetooth and Wi-Fi, such as online
cards and coins, my personal Wi-Fi and wallets, stocks, currencies,
exchanges, tokens and calendars and all contacts and e-mails and
information inside it and work sites and cloud spaces and... They have
deleted all the information on my phone, laptop and flash drive. The
identification cards related to my social, economic, political affairs and
the police force are also available. There are many mi accounts created
with my information that I do not have access to.and business tools through
Bluetooth and Wi-Fi, such as online cards, coins, my personal Wi-Fi, and
wallets, stocks, currencies, exchanges, tokens, and calendars, and all
contacts, e-mails, and information inside it, and business sites and
spaces. They deleted the cloud and... and took all the information on the
phone, laptop and flash drive Identification cards related to my social,
economic, political affairs and the police force are also available. There
are many mi accounts created with my details that I do not have access to.
Safura Rezaei's email with the numbers 09369174690 and 09139284159 and
Yusuf Rezaei's email with the phone numbers 09135693241 and 091333312805
09393359338 and 09933386516 and
09939322100 and Yusuf Rezaei's national code is 1080118799, I have this
information from them

And the important point is that Safura Rezaei and Yusuf Rezaei baited their
sister Samane Rezaei and used Samane Rezaei's phone, emails and numbers and
did all these actions. He did not have them and he also did not have access
to his emails and was completely unaware. The number of people involved is
not completely clear because all the contacts and personal and business
information are available on my phone and website and it is not clear how
many people are involved. Please check and take action immediately and
inform me. My emails are not secure. They have all my personal information
such as national code and number and.. all my details and my government
information. The amount is 146 million dollars, 33.5 million dollars and
312 million dollars in the email khlylkhatwnltfy@ gmail.com is available as
blockchain. The emails of Khatoon 786898, Majid Lotfi Jalalabadi and Khalil
Khatoon Lotfi are my emails and they have also created a fake website with
my emails and details.call09923550876 to inform.


در تاریخ پنجشنبه ۲۹ فوریه ۲۰۲۴،‏ ۱۷:۱۵ Dmitry Chestnykh <
***@***.***> نوشت:
