### ISSUE TITLE
Add usage examples to docs

### ISSUE THREAD

**Issue by dchest** [dchest/tweetnacl-js#32]
Any takers? :-)

**Comment by dchest** [comment]
* Fixed incomplete return types in TypeScript typings.
* Replaced COPYING.txt with LICENSE file, which now has public domain dedication
  text from The Unlicense. License fields in package.json and bower.json have
  been set to "Unlicense". The project was and will be in the public domain --
  this change just makes it easier for automated tools to know about this fact by
  using the widely recognized and SPDX-compatible template for public domain
  dedication.

**Comment by tobiasmuecksch** [comment]
Anything new on this issue?

**Comment by dchest** [comment]
Nope, still "help needed" :)

**Comment by joeldrapper** [comment]
Can I help with this?

**Comment by dchest** [comment]
@joeldrapper Sure, that would be great! We can collaborate on this wiki page: https://github.com/dchest/tweetnacl-js/wiki/Examples Not sure how GitHub wiki works — can you edit it? If so, please feel free to add examples there.

**Comment by dchest** [comment]
@bkniffler thanks, will check it out.

>  I was surprised to see that anyone can edit wiki pages..

The power of the original WikiWikiWeb! :D (although probably not a good idea for a crypto library?)

**Comment by bkniffler** [comment]
I added another example for box :)

**Comment by sshelton76** [comment]
@bkniffler I think I speak for everyone when I say great job on the box code.  However the example would have been more clear had you not used typescript and for encryption it would have been better to have
used 
```
nacl.box(message, nonce, theirPublicKey, mySecretKey) 
```
and skipped out on the precomputed sharedkey step.  

If you look at https://github.com/dchest/tweetnacl-js/blob/master/nacl.js lines 998 and 1013 you can see that computing the shared key is already done.  So unless there is a specific reason to pre-cache the sharedkey there is no purpose in calling it out as a separate step.  I would argue that pre-caching the key while perhaps enhancing performance somewhat, is also very unsafe in a javascript context, since it would be available to any attacker.

**Comment by noncash15** [comment]
Ok
