### ISSUE TITLE
Need a better module wrapping

### ISSUE THREAD

**Issue by dchest** [dchest/tweetnacl-js#66]
We need something like [UMD](https://github.com/umdjs/umd) for module wrapping with these features:

* [ ] Global `nacl`/`window.nacl`.
* [ ] CommonJS:
 * [ ] Node.js, with PRNG using `require('crypto')`
 * [ ] Browserify/Webpack using WebCrypto, not `require('crypto')` emulation ([without this workaround](https://github.com/dchest/tweetnacl-js/wiki/Using-with-Webpack)).
* [ ] AMD
* [ ] `root` object inside the module, which can be `null` or `undefined` for Node, `window` for browsers, `self` (?) for webworkers in browsers (to fix #65)

**Comment by jo** [comment]
I suggest depending on browserify for this:

* Write tweetnacl in pure node
* Use https://github.com/crypto-browserify/randombytes
* `browserify nacl-fast.js -s nacl > dist/nacl-fast.js`

This solves all the requirements stated above, except AMD support.
Its the route we took successfully with [PouchDB](https://github.com/pouchdb/pouchdb/).

If you like I can pour this into a PR.

**Comment by dchest** [comment]
Thanks, I'll think about it, but I don't want to introduce another build tool just for a few lines of code.

**Comment by jo** [comment]
I totally understand your objections. Just to add: since here is already a build step (uglifyjs) it does not add more maintenance efford. And browserify has been made exactly for this purpose.

**Comment by dchest** [comment]
@RainaBatwing do you think it will solve #59?

@jo where can I take a look at what browserify replaces Buffer with? Thanks!

**Comment by jo** [comment]
https://github.com/feross/buffer

**Comment by dchest** [comment]
@jo thank you! It's kinda big, but would solve #44, #38, and #59. Unfortunately, it's using MIT license, and I'd like to keep TweetNaCl public domain. Maybe I can write my own? :-) Does browserify allows custom replacements for Node objects?

**Comment by jo** [comment]
Yes, I think in _package.json_ you can just point to a file or (a node module):

```json
"browser": {
  "buffer": "./lib/buffer.js"
}
```
https://github.com/substack/node-browserify#browser-field

Extensive docu can be found in the [Browserify Handbook](https://github.com/substack/browserify-handbook).

**Comment by RainaBatwing** [comment]
I would like to see this change, but I'd much rather you use the browserify Buffer than invent a new one. MIT license is not a restrictive one, and having more code that can potentially introduce bugs seems antithetical to the spirit of tweetnacl as a small audit-able library.

If there really are users who cannot use MIT-licensed software but can accept third party public domain code, they could open an issue later and we can reconsider then?

**Comment by dchest** [comment]
Thanks for opinions, everyone. I'm sorry that I'm so picky about this change, but I just can't handle this little fact:

* Buffer.js — 38 KB
* nacl.js — 33 KB

I know, an average image on a website is bigger than that, but still I'd like to avoid this. Especially, since Buffer is here mostly for Node.js, which is better served by a native NaCl.

**Comment by alax** [comment]
So it seems like the arguments are:

Node Buffers (and browserify shim):
- One code base to audit for buffers
- In theory, better audited since it's more widely used
- More consistent buffer implementations
- Solves a few outlying bugs

TweetNaCl typed arrays:
- Typed arrays are native to the browser
- Small, concise code that should be easy to audit

Personally, I'd say stick with the typed arrays, since it does make more sense in the browser. TweetNaCl is great for the client-side, and if you'd like to run it under Node, that's easily doable even with the typed arrays. But, like @dchest mentioned, under Node you really could just use a library with native NaCl bindings, which would definitely offer better performance, and would probably use buffers as well.

So, +1 for the current implementation from me. Small and simple on the client-side, but still fairly simple to use on the server-side if necessary.

**Comment by dchest** [comment]
Another option is to implement both Buffers and typed arrays as @RainaBatwing proposed in #59. If you pass a Buffer to functions, they will return Buffers, if you pass a typed array, they will return typed arrays.

**Comment by RainaBatwing** [comment]
My interest in using tweetnacl-js is because I'm developing cross platform p2p apps using NW.js and depending on platform-specific code makes software update distribution much more complicated. I'd like to have just one version which works on every platform, and I'd like all the application specific code to be in javascript, so anyone can take it and alter it easily. I strongly dislike the idea of shipping binary packages, but most users do not have C build tools on their computer.

**Comment by tarun1475** [comment]
Use react-native-tweetnacl npm package for using tweetnacl in mobile apps.
