### ISSUE TITLE
timing attacks

### ISSUE THREAD

**Issue by timkuijsten** [dchest/tweetnacl-js#80]
Your answer about whether this library protects against a timing side-channel attack is "Hopefully, as best as it could be done in JavaScript." in https://github.com/dchest/tweetnacl-js/issues/73. Are you talking about https://github.com/dchest/tweetnacl-js#constant-time-comparison?

I wonder if any claim can be made about this library being safe from side-channels since it's an important part of the original NaCl source code and design and something that NaCl is known to protect against. People might not be aware of any differences in security of the C version of NaCl versus any port to a higher-level language.

Just opened up a related question with more references to the problem of JS crypto side-channel resistance in the libsodium.js issue tracker: https://github.com/jedisct1/libsodium.js/issues/21

**Comment by dchest** [comment]
I don't think such claim can't be made about any JavaScript code, because you just don't know how the interpreter/JIT compiler will act. For example, if a VM uses tagged pointers, it probably puts small numbers directly into the pointer, but allocates larger numbers in the heap. This may lead to differences in timing between allocating number 1 and, say, number 2147483648. Of course, there's no guarantee that a C compiler or even a CPU doesn't do this, but it's generally accepted (and can be verified) that it does no such things.

As for TweetNaCl-js specifically, there is nothing in it that I can point to and say "this is not constant time": the algorithms are all the same constant-time algorithms directly ported from TweetNaCl (or other sources for the fast version). But I also can't make a claim that TweetNaCl-js is free of side channels: it is so *by design*, but may not be true considering *implementation* language.

**Comment by dchest** [comment]
To add: can we investigate/test if it's side-channel safe? In theory — yes, in practice, I think, it's infeasible: who will do this for every version of every evergreen VMs (V8, SpiderMonkey, JavaScriptCore, Chakra)?

**Comment by timkuijsten** [comment]
These are interesting questions. I can imagine the only practical and secure way forward is to rely on the environment, i.e. WebCrypto. But WebCrypto does not seem to have all the primitives to support NaCl. At least Curve25519 is still missing: https://www.w3.org/Bugs/Public/show_bug.cgi?id=25839

**Comment by timkuijsten** [comment]
On a different note, are you aware of any TweetNaCl implementation that uses native c/c++ bindings like https://github.com/paixaop/node-sodium?

**Comment by dchest** [comment]
No, I'm not aware of such implementations.
