### ISSUE TITLE
UTF-8 codec functions are named the wrong way round

### ISSUE THREAD

**Issue by infinity0** [dchest/tweetnacl-js#84]
Hi, in the context of UTF-8, "encode" is generally taken to mean string (of unicode characters, like in JS) -> [byte], and "decode" means [byte] -> string. Every single other API in existence has these semantics.

Even the implementation gives a clue - `nacl.util.decodeUTF8` calls `unescape(encodeURIComponent(s))`, which is the standard JS way to encode a Unicode string into a "UTF-8 string" where each 16-bit character has only 8 semantic bits and the higher 8 bits are not set.

Please deprecate this API and create a new API with correct names, before this turns into a hilariously bad security hole.

**Comment by dchest** [comment]
You're right, the confusion here appeared most likely due to the fact that we're not converting unicode runes, but UTF16 strings, so the meaning of these functions here are *decode(fromUTF16into)UTF8* and *encodeUTF8(intoUTF16string)*, so it's a bit different from other languages that have types for Unicode characters.

I intend to completely deprecate and remove *util* functions in the future, but it won't be soon.
